# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: key-val.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'key-val.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkey-val.proto\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t2]\n\rKeyValueStore\x12%\n\x06PutKey\x12\x0b.PutRequest\x1a\x0c.PutResponse\"\x00\x12%\n\x06GetKey\x12\x0b.GetRequest\x1a\x0c.GetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_val_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=17
  _globals['_PUTREQUEST']._serialized_end=57
  _globals['_PUTRESPONSE']._serialized_start=59
  _globals['_PUTRESPONSE']._serialized_end=89
  _globals['_GETREQUEST']._serialized_start=91
  _globals['_GETREQUEST']._serialized_end=116
  _globals['_GETRESPONSE']._serialized_start=118
  _globals['_GETRESPONSE']._serialized_end=146
  _globals['_KEYVALUESTORE']._serialized_start=148
  _globals['_KEYVALUESTORE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
